# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: atlassian/default-image:latest

# EX0

# Build step compiles the frontend resource into the dist folder
# Deploy step packages that along with the backend files and deploys code to AWS

pipelines:
  default:
    - step:
        image: node:7.1.0
        name: Build
        caches:
          - node
        script:
          - npm install
          - npm run build
        artifacts:
          - dist/**
    - step:
        name: Deploy
        caches:
          - pip
        image: python:3.5.1
        script:
          - apt-get update && apt-get install -y zip
          - pip install boto3==1.3.0
          - zip -r /tmp/artifact.zip .nvmrc package.json appspec.yml config/* scripts/* server/* dist/*
          - python deploy.py