version: "3"
services:
  rethink:
    image: 'rethinkdb'
    ports:
      - "8080:8080"
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/usr/src/app"
    links:
      - rethink